In [1]:
import pandas as pd
from sklearn.model_selection import KFold
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#Reading the Auto Dataset.
dataframe = pd.read_csv("auto-mpg_1.csv")
print(dataframe.shape)
dataframe.head(3)

(392, 9)


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite

In [5]:
#Now, selecting the independent and dependent varriables.
X_predictors = dataframe.drop(["horsepower","car name"],axis = 1)
Y_target = dataframe["horsepower"]

#Printing the shape.
print(Y_target.shape, X_predictors.shape)
X_predictors.head(3)

(392,) (392, 7)


mpg  cylinders  displacement  weight  acceleration  model year  origin
0  18.0          8         307.0    3504          12.0          70       1
1  15.0          8         350.0    3693          11.5          70       1
2  18.0          8         318.0    3436          11.0          70       1

In [9]:
#THis is to run a normal Linear Regression model, to check.
#We are making training and testing sets.
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_predictors, Y_target, test_size = 0.2 )

In [10]:
#Making the Linear Regression object and fit and finding score.
lr = LinearRegression()
lr.fit(x_train,y_train)

#The score keeps changing if, you again compile the train and test splits.
lr.score(x_test, y_test)

0.9042853410593559

In [11]:
#The Real k-fold cross validation with 10 folds.

from sklearn.model_selection import KFold
kf = KFold(n_splits = 10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [12]:
#Example to understand k -fold
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,11,10]):
    print(train_index,test_index)

[ 2  3  4  5  6  7  8  9 10] [0 1]
[ 0  1  3  4  5  6  7  8  9 10] [2]
[ 0  1  2  4  5  6  7  8  9 10] [3]
[ 0  1  2  3  5  6  7  8  9 10] [4]
[ 0  1  2  3  4  6  7  8  9 10] [5]
[ 0  1  2  3  4  5  7  8  9 10] [6]
[ 0  1  2  3  4  5  6  8  9 10] [7]
[ 0  1  2  3  4  5  6  7  9 10] [8]
[ 0  1  2  3  4  5  6  7  8 10] [9]
[0 1 2 3 4 5 6 7 8 9] [10]


In [13]:
#Function used to find score .
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    
    return model.score(x_test, y_test)

In [14]:
#this is where our k fold works and score is appended into scores_lr
scores_lr = []

for train_index, test_index in kf.split(X_predictors):
    x_train, x_test, y_train, y_test = X_predictors.iloc[train_index], X_predictors.iloc[test_index], Y_target.iloc[train_index], Y_target.iloc[test_index]
    
    scores_lr.append((get_score(LinearRegression(), x_train, x_test, y_train, y_test)))

In [15]:
#list of all the score in each fold.
scores_lr

[0.7769511931413693,
 0.9297795958893821,
 0.9083762508446727,
 0.8685455357879031,
 0.8251968776757439,
 0.9274511733701327,
 0.8363358560264653,
 0.9036170592332304,
 0.825527590917848,
 0.34763711082714766]

In [16]:
#This is the actual score of the model with k-fold cross validation.
print(np.mean(scores_lr))

0.8149418243713896
